/**
 * Generate explicit OpenTAP TestStep classes from spec/opentap-operations.json.
 */
const root = new URL("..", import.meta.url);
const manifestPath = new URL("spec/opentap-operations.json", root);
const outputDir = new URL("dotnet/src/InstrumentComponents.OpenTap/Steps/Generated/", root);

interface Parameter {
  name: string;
  displayName: string;
  type: string;
  enumType?: string;
  order: number;
  unit?: string;
  default?: unknown;
}

interface Invoke {
  method: string;
  returns?: string;
  args?: { parameter: string }[];
}

interface Operation {
  id: string;
  stepTypeName: string;
  implementation: string;
  kind: string;
  instrumentKind: string;
  instrumentType: string;
  accessor: string;
  displayName: string;
  displayGroups: string[];
  description?: string;
  parameters?: Parameter[];
  invoke?: Invoke;
  publish: { mode: string; name?: string; unit?: string; supportsLimits?: boolean };
}

interface Manifest {
  operations: Operation[];
}

const INHERITED_LIMITS = new Set(["LimitLow", "LimitHigh"]);
const INHERITED_SAMPLES = new Set(["Channel", "SampleCount", "IntervalMs"]);
const GENERATED_HEADER = "// <auto-generated by tools/gen-opentap-steps.ts />";

function csharpType(parameter: Parameter): string {
  return {
    string: "string",
    int: "int",
    uint: "uint",
    double: "double",
    bool: "bool",
    nullableDouble: "double?",
    enum: parameter.enumType ?? "string",
  }[parameter.type] ?? "object";
}

function defaultSuffix(parameter: Parameter): string {
  if (parameter.default === undefined) return "";
  if (parameter.type === "string") return ` = ${JSON.stringify(parameter.default)}`;
  if (parameter.type === "bool") return ` = ${parameter.default ? "true" : "false"}`;
  if (parameter.type === "enum") return ` = ${parameter.enumType}.${parameter.default}`;
  return ` = ${parameter.default}`;
}

function groupsLiteral(groups: string[]): string {
  return groups.map((group) => JSON.stringify(group)).join(", ");
}

function emittedParameters(operation: Operation): Parameter[] {
  return (operation.parameters ?? []).filter((parameter) =>
    !INHERITED_LIMITS.has(parameter.name) && !INHERITED_SAMPLES.has(parameter.name)
  );
}

function emitProperty(parameter: Parameter): string {
  const unit = parameter.unit ? `\n    [Unit(${JSON.stringify(parameter.unit)})]` : "";
  return `    [Display(${JSON.stringify(parameter.displayName)}, Order: ${parameter.order})]${unit}
    public ${csharpType(parameter)} ${parameter.name} { get; set; }${defaultSuffix(parameter)}`;
}

function callArgs(operation: Operation): string {
  const args = operation.invoke?.args ?? [];
  if (args.length === 0) return "";
  return args.map((arg) => arg.parameter).join(", ");
}

function needsClassesUsing(operations: Operation[]): boolean {
  return operations.some((operation) =>
    (operation.parameters ?? []).some((parameter) => parameter.type === "enum")
  );
}

function emitScalarStep(operation: Operation): string {
  const parameters = emittedParameters(operation);
  const properties = parameters.map(emitProperty).join("\n\n");
  const resultName = operation.publish.name ?? operation.displayName;
  const unit = operation.publish.unit ?? "";
  const args = callArgs(operation);
  const invoke = `instrument.${operation.accessor}.${operation.invoke!.method}(${args})`;
  const valueExpr = operation.invoke!.returns === "bool" ? `${invoke} ? 1.0 : 0.0` : invoke;
  return `[Display(${JSON.stringify(operation.displayName)}, Groups: [${groupsLiteral(operation.displayGroups)}], Description: ${JSON.stringify(operation.description ?? "")})]
public sealed class ${operation.stepTypeName} : OptionalLimitStep<${operation.instrumentType}>
{
${properties ? properties + "\n\n" : ""}    public override void Run()
    {
        if (!TryGetInstrument(out var instrument))
            return;

        PublishScalar(${JSON.stringify(resultName)}, ${valueExpr}, ${JSON.stringify(unit)});
    }
}`;
}

function emitCommandStep(operation: Operation): string {
  const parameters = emittedParameters(operation);
  const properties = parameters.map(emitProperty).join("\n\n");
  const args = callArgs(operation);
  return `[Display(${JSON.stringify(operation.displayName)}, Groups: [${groupsLiteral(operation.displayGroups)}], Description: ${JSON.stringify(operation.description ?? "")})]
public sealed class ${operation.stepTypeName} : InstrumentBoundStep<${operation.instrumentType}>
{
${properties ? properties + "\n\n" : ""}    public override void Run()
    {
        if (!TryGetInstrument(out var instrument))
            return;

        instrument.${operation.accessor}.${operation.invoke!.method}(${args});
        UpgradeVerdict(Verdict.Pass);
    }
}`;
}

function emitSampleTraceStep(operation: Operation): string {
  const parameters = emittedParameters(operation);
  const properties = parameters.map(emitProperty).join("\n\n");
  const args = callArgs(operation);
  const channel = operation.publish.name ?? "Trace";
  return `[Display(${JSON.stringify(operation.displayName)}, Groups: [${groupsLiteral(operation.displayGroups)}], Description: ${JSON.stringify(operation.description ?? "")})]
public sealed class ${operation.stepTypeName} : InstrumentBoundStep<${operation.instrumentType}>
{
${properties ? properties + "\n\n" : ""}    public override void Run()
    {
        if (!TryGetInstrument(out var instrument))
            return;

        var samples = instrument.${operation.accessor}.${operation.invoke!.method}(${args});
        for (var i = 0; i < samples.Count; i++)
            PhaseIResults.PublishSample(Results, ${JSON.stringify(channel)}, i, samples[i]);
        UpgradeVerdict(Verdict.Pass);
    }
}`;
}

function emitOperation(operation: Operation): string {
  if (operation.kind !== "invoke" || operation.invoke == null) {
    throw new Error(`${operation.id}: generated operations must be kind invoke`);
  }
  const returns = operation.invoke.returns;
  const mode = operation.publish.mode;
  if ((returns === "double" || returns === "bool") && mode === "scalar") {
    return emitScalarStep(operation);
  }
  if (returns === "void" && mode === "none") {
    return emitCommandStep(operation);
  }
  if (returns === "trace" && mode === "sample") {
    return emitSampleTraceStep(operation);
  }
  throw new Error(`${operation.id}: unsupported generated shape ${returns}/${mode}`);
}

function emitFile(kind: string, operations: Operation[]): string {
  const classesUsing = needsClassesUsing(operations) ? "using InstrumentComponents.Classes;\n" : "";
  const body = operations.map(emitOperation).join("\n\n");
  return `${GENERATED_HEADER}
${classesUsing}using OpenTap;

namespace InstrumentComponents.OpenTap;

${body}
`;
}

function main() {
  const manifest = JSON.parse(Deno.readTextFileSync(manifestPath)) as Manifest;
  const generated = manifest.operations
    .filter((operation) => operation.implementation === "generated")
    .sort((a, b) => a.stepTypeName.localeCompare(b.stepTypeName));
  if (generated.length === 0) {
    throw new Error("no generated operations in spec/opentap-operations.json");
  }

  Deno.mkdirSync(outputDir, { recursive: true });
  for (const stale of Deno.readDirSync(outputDir)) {
    if (stale.isFile && stale.name.endsWith(".g.cs")) {
      Deno.removeSync(new URL(stale.name, outputDir));
    }
  }

  const byKind = new Map<string, Operation[]>();
  for (const operation of generated) {
    const list = byKind.get(operation.instrumentKind) ?? [];
    list.push(operation);
    byKind.set(operation.instrumentKind, list);
  }
  for (const [kind, operations] of [...byKind.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    Deno.writeTextFileSync(new URL(`${kind}Steps.g.cs`, outputDir), emitFile(kind, operations));
  }

  const names = generated.map((operation) => `        typeof(${operation.stepTypeName}),`).join("\n");
  const catalog = `${GENERATED_HEADER}
namespace InstrumentComponents.OpenTap;

public static class GeneratedOperationCatalog
{
    public static readonly Type[] StepTypes =
    [
${names}
    ];
}
`;
  Deno.writeTextFileSync(new URL("OperationCatalog.g.cs", outputDir), catalog);
}

main();
