/**
 * Generate Rust + C# sources from capability_probes.toml and scpi_commands.toml.
 */
import { rustfmtGenerated } from "./rustfmt-generated.ts";

const root = new URL("..", import.meta.url);
const probesToml = await Deno.readTextFile(
  new URL("crates/instrument-core/data/capability_probes.toml", root),
);
const scpiToml = await Deno.readTextFile(
  new URL("crates/instrument-core/data/scpi_commands.toml", root),
);

function parseSimpleToml(text: string): Record<string, unknown> {
  const result: Record<string, unknown> = {};
  let section: string | null = null;
  for (const raw of text.split("\n")) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const sec = line.match(/^\[([^\]]+)\]$/);
    if (sec) {
      section = sec[1];
      if (!(section in result)) result[section] = {};
      continue;
    }
    const eq = line.indexOf("=");
    if (eq < 0) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    let parsed: unknown = value;
    if (value.startsWith('"') && value.endsWith('"')) {
      parsed = value.slice(1, -1).replace(/\\"/g, '"').replace(/\\\\/g, "\\");
    } else if (value.startsWith("[") && value.endsWith("]")) {
      parsed = value
        .slice(1, -1)
        .split(",")
        .map((s) => s.trim().replace(/^"|"$/g, ""))
        .filter(Boolean);
    } else if (/^\d+$/.test(value)) {
      parsed = Number(value);
    }
    if (section) {
      (result[section] as Record<string, unknown>)[key] = parsed;
    } else {
      result[key] = parsed;
    }
  }
  return result;
}

function snakeToPascal(s: string): string {
  return s.split("_").map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join("");
}

function snakeToCamel(s: string): string {
  const p = snakeToPascal(s);
  return p.charAt(0).toLowerCase() + p.slice(1);
}

const probes = parseSimpleToml(probesToml);
const scpi = parseSimpleToml(scpiToml);
const timeoutMs = Number(probes.probe_timeout_ms ?? 800);

const readonlyKeys = [
  "dmm",
  "psu",
  "fgen",
  "scope",
  "switch",
  "counter",
  "pwrmeter",
  "specan",
] as const;
const rustConstName: Record<string, string> = {
  dmm: "DMM_READONLY_COMMANDS",
  psu: "PSU_READONLY_COMMANDS",
  fgen: "FGEN_READONLY_COMMANDS",
  scope: "SCOPE_READONLY_COMMANDS",
  switch: "SWITCH_READONLY_COMMANDS",
  counter: "COUNTER_READONLY_COMMANDS",
  pwrmeter: "PWRMETER_READONLY_COMMANDS",
  specan: "SPECAN_READONLY_COMMANDS",
};
const csConstName: Record<string, string> = {
  dmm: "DmmReadonlyCommands",
  psu: "PsuReadonlyCommands",
  fgen: "FgenReadonlyCommands",
  scope: "ScopeReadonlyCommands",
  switch: "SwitchReadonlyCommands",
  counter: "CounterReadonlyCommands",
  pwrmeter: "PwrmeterReadonlyCommands",
  specan: "SpecanReadonlyCommands",
};

function formatRustStrArray(name: string, commands: string[]): string {
  if (commands.length <= 4) {
    return `pub const ${name}: &[&str] = &[${commands.map((c) => `"${c}"`).join(", ")}];`;
  }
  const lines = commands.map((c) => `    "${c}",`).join("\n");
  return `pub const ${name}: &[&str] = &[\n${lines}\n];`;
}

function formatCsStrArray(name: string, commands: string[]): string {
  if (commands.length <= 4) {
    return `    internal static readonly string[] ${name} =\n        [${commands.map((c) => `"${c}"`).join(", ")}];`;
  }
  return `    internal static readonly string[] ${name} =\n        [${commands.map((c) => `"${c}"`).join(", ")}];`;
}

// --- Rust probes ---
let rustProbes = `// @generated by tools/gen-shared-tables.ts — do not edit by hand
use crate::scpi::ScpiSession;
use std::time::Duration;

pub const PROBE_TIMEOUT: Duration = Duration::from_millis(${timeoutMs});

`;
for (const key of readonlyKeys) {
  const section = probes[`readonly.${key}`] as { commands?: string[] };
  rustProbes += formatRustStrArray(rustConstName[key], section.commands ?? []) + "\n\n";
}
const acq = probes["acquisition.dmm"] as { commands?: string[] };
rustProbes += formatRustStrArray("DMM_ACQUISITION_COMMANDS", acq.commands ?? []) + "\n\n";
rustProbes += `/// Validate instrument-specific reply shapes rather than accepting any transport success.
pub fn valid_probe_reply(command: &str, response: &str) -> bool {
    let cmd = command.trim_start_matches(':').to_ascii_uppercase();
    let reply = response.trim().trim_matches('"').to_ascii_uppercase();
    if reply.is_empty() || crate::scpi::is_syst_err_supported_reply(&reply) { return false; }
    if cmd.contains("FUNC") {
        return if cmd.starts_with("SOUR") { ["SIN", "SQU", "RAMP", "PULS", "NOIS", "DC", "ARB", "USER"].contains(&reply.as_str()) }
        else { ["VOLT", "VOLT:DC", "VOLT:AC", "CURR", "CURR:DC", "CURR:AC", "RES", "FRES", "FREQ", "PER", "CONT", "DIOD", "TEMP", "CAP"].contains(&reply.as_str()) };
    }
    if cmd.starts_with("OUTP") || cmd.contains("AUTO?") { return ["0", "1", "OFF", "ON"].contains(&reply.as_str()); }
    if cmd.starts_with("UNIT") { return ["DBM", "W", "WATT"].contains(&reply.as_str()); }
    if cmd.starts_with("WAV") { return reply.strip_prefix("CHAN").and_then(|s| s.parse::<u32>().ok()).is_some_and(|n| n > 0); }
    if cmd.starts_with("ROUT") { return ["0", "1"].contains(&reply.as_str()) || reply.strip_prefix("(@").and_then(|s| s.strip_suffix(')')).is_some_and(|s| s.chars().all(|c| c.is_ascii_digit() || [',', ':', ' '].contains(&c))); }
    let signed_voltage = matches!(cmd.as_str(), "MEAS:VOLT:DC?" | "VOLT? (@1)");
    reply.parse::<f64>().is_ok_and(|n| n.is_finite() && (signed_voltage || n >= 0.0))
}

/// Returns true when a probe produces valid capability evidence.
pub fn probe_any(session: &mut ScpiSession, commands: &[&str], timeout: Duration) -> bool {
    commands
        .iter()
                .any(|cmd| session.query_with_timeout(cmd, timeout).is_ok_and(|reply| valid_probe_reply(cmd, &reply)))
        && (commands != PSU_READONLY_COMMANDS || session.query_with_timeout(":VOLT? (@1)", timeout).is_ok_and(|reply| valid_probe_reply(":VOLT? (@1)", &reply)))
}
`;

// --- Rust SCPI commands ---
const consts = (scpi.const ?? {}) as Record<string, string>;
const optionalRange = (scpi.optional_range ?? {}) as Record<string, string>;
const templates = (scpi.template ?? {}) as Record<string, string>;
const configureSections = Object.keys(scpi).filter((k) =>
  k.startsWith("dmm_configure_")
);

let rustScpi = `// @generated by tools/gen-shared-tables.ts — do not edit by hand

`;
for (const [key, value] of Object.entries(consts)) {
  rustScpi += `pub const ${key.toUpperCase()}: &str = "${value}";\n`;
}
rustScpi += "\n";

for (const [key, base] of Object.entries(optionalRange)) {
  rustScpi += `pub fn ${key}(range: Option<f64>) -> String {
    match range {
        Some(r) => format!("{base} {r}"),
        None => "${base}".into(),
    }
}

`.replaceAll("{base}", base);
}

// Templates: extract placeholders
function templateArgs(tmpl: string): string[] {
  const args: string[] = [];
  const re = /\{([a-z0-9_]+)\}/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(tmpl))) {
    if (!args.includes(m[1])) args.push(m[1]);
  }
  return args;
}

function rustArgType(name: string): string {
  if (name === "channel" || name === "ch1" || name === "ch2" || name === "count") {
    return "u32";
  }
  if (name === "enabled") return "bool";
  if (
    name === "state" || name === "scpi_name" || name === "source" ||
    name === "slope" || name === "coupling" || name === "unit"
  ) {
    return "&str";
  }
  return "f64";
}

function csArgType(name: string): string {
  if (name === "channel" || name === "ch1" || name === "ch2" || name === "count") {
    return "uint";
  }
  if (name === "enabled") return "bool";
  if (
    name === "state" || name === "scpi_name" || name === "source" ||
    name === "slope" || name === "coupling" || name === "unit"
  ) {
    return "string";
  }
  return "double";
}

function emitConfigureFn(
  key: string,
  conf: Record<string, string>,
): { rust: string; cs: string } {
  const rustName = key;
  const csName = snakeToPascal(key);
  const withRr = conf.with_range_resolution!
    .replace("{range}", "{r}")
    .replace("{resolution}", "{res}");
  const withR = conf.with_range!.replace("{range}", "{r}");
  const withRes = conf.with_resolution!.replace("{resolution}", "{res}");
  const csWithRr = conf.with_range_resolution!
    .replace("{range}", "{ScpiFormat.Double(r)}")
    .replace("{resolution}", "{ScpiFormat.Double(res)}");
  const csWithR = conf.with_range!.replace("{range}", "{ScpiFormat.Double(r)}");
  const csWithRes = conf.with_resolution!.replace("{resolution}", "{ScpiFormat.Double(res)}");
  const rust = `pub fn ${rustName}(range: Option<f64>, resolution: Option<f64>) -> String {
    match (range, resolution) {
        (Some(r), Some(res)) => format!("${withRr}"),
        (Some(r), None) => format!("${withR}"),
        (None, Some(res)) => format!("${withRes}"),
        (None, None) => "${conf.base}".into(),
    }
}`;
  const cs = `    public static string ${csName}(double? range, double? resolution) => (range, resolution) switch
    {
        ({ } r, { } res) => $"${csWithRr}",
        ({ } r, null) => $"${csWithR}",
        (null, { } res) => $"${csWithRes}",
        _ => "${conf.base}",
    };`;
  return { rust, cs };
}

for (const [key, tmpl] of Object.entries(templates)) {
  if (key.includes("output_enable")) {
    // special: bool enabled → ON/OFF state string in callers; keep template with {state}
  }
  const args = templateArgs(tmpl);
  const rustParams = args.map((a) => `${a}: ${rustArgType(a)}`).join(", ");
  const rustTmpl = tmpl.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  rustScpi += `pub fn ${key}(${rustParams}) -> String {
    format!("${rustTmpl}")
}

`;
}

for (const key of configureSections) {
  const conf = scpi[key] as Record<string, string>;
  rustScpi += emitConfigureFn(key, conf).rust + "\n\n";
}

// --- C# CapabilityProbes ---
let csProbes = `// <auto-generated by tools/gen-shared-tables.ts />
using InstrumentComponents.Scpi;

namespace InstrumentComponents.Classifier;

internal static class CapabilityProbes
{
    internal static readonly TimeSpan ProbeTimeout = TimeSpan.FromMilliseconds(${timeoutMs});

`;
for (const key of readonlyKeys) {
  const section = probes[`readonly.${key}`] as { commands?: string[] };
  csProbes += formatCsStrArray(csConstName[key], section.commands ?? []) + "\n\n";
}
csProbes += formatCsStrArray("DmmAcquisitionCommands", acq.commands ?? []) + "\n\n";
csProbes += `    internal static bool ValidProbeReply(string command, string response)
    {
        var cmd = command.TrimStart(':').ToUpperInvariant();
        var reply = response.Trim().Trim('"').ToUpperInvariant();
        if (reply.Length == 0 || ScpiProtocol.IsSystErrSupportedReply(reply)) return false;
        if (cmd.Contains("FUNC"))
        {
            if (cmd.StartsWith("SOUR")) return new[] { "SIN", "SQU", "RAMP", "PULS", "NOIS", "DC", "ARB", "USER" }.Contains(reply);
            return new[] { "VOLT", "VOLT:DC", "VOLT:AC", "CURR", "CURR:DC", "CURR:AC", "RES", "FRES", "FREQ", "PER", "CONT", "DIOD", "TEMP", "CAP" }.Contains(reply);
        }
        if (cmd.StartsWith("OUTP") || cmd.Contains("AUTO?")) return reply is "0" or "1" or "OFF" or "ON";
        if (cmd.StartsWith("UNIT")) return reply is "DBM" or "W" or "WATT";
        if (cmd.StartsWith("WAV")) return reply.StartsWith("CHAN") && uint.TryParse(reply[4..], out var channel) && channel > 0;
        if (cmd.StartsWith("ROUT")) return reply is "0" or "1" || reply.StartsWith("(@") && reply.EndsWith(")") && reply[2..^1].All(c => char.IsAsciiDigit(c) || c is ',' or ':' or ' ');
        var signedVoltage = cmd is "MEAS:VOLT:DC?" or "VOLT? (@1)";
        return double.TryParse(reply, System.Globalization.NumberStyles.Float, System.Globalization.CultureInfo.InvariantCulture, out var number) && double.IsFinite(number) && (signedVoltage || number >= 0);
    }

    public static bool ProbeAny(ScpiSession session, string[] commands, TimeSpan timeout)
    {
        foreach (var cmd in commands)
        {
            try
            {
                var reply = session.QueryWithTimeout(cmd, timeout);
                if (!ValidProbeReply(cmd, reply)) continue;
                if (ReferenceEquals(commands, PsuReadonlyCommands) && !ValidProbeReply(":VOLT? (@1)", session.QueryWithTimeout(":VOLT? (@1)", timeout))) continue;
                return true;
            }
            catch
            {
                // try next spelling
            }
        }
        return false;
    }

    public static async Task<bool> ProbeAnyAsync(AsyncScpiSession session, string[] commands, TimeSpan timeout, CancellationToken cancellationToken = default)
    {
        foreach (var cmd in commands)
        {
            try
            {
                var reply = await session.QueryWithTimeoutAsync(cmd, timeout, cancellationToken).ConfigureAwait(false);
                if (!ValidProbeReply(cmd, reply)) continue;
                if (ReferenceEquals(commands, PsuReadonlyCommands) && !ValidProbeReply(":VOLT? (@1)", await session.QueryWithTimeoutAsync(":VOLT? (@1)", timeout, cancellationToken).ConfigureAwait(false))) continue;
                return true;
            }
            catch (OperationCanceledException) { throw; }
            catch
            {
                // try next spelling
            }
        }
        return false;
    }
}
`;

// --- C# ScpiCommands ---
let csScpi = `// <auto-generated by tools/gen-shared-tables.ts />
using InstrumentComponents.Scpi;

namespace InstrumentComponents.Classes;

internal static class ScpiCommands
{
`;

for (const [key, base] of Object.entries(optionalRange)) {
  const name = snakeToPascal(key);
  csScpi += `    public static string ${name}(double? range) =>
        range is { } r ? $"${base} {ScpiFormat.Double(r)}" : "${base}";

`;
}

for (const key of configureSections) {
  const conf = scpi[key] as Record<string, string>;
  csScpi += emitConfigureFn(key, conf).cs + "\n\n";
}

for (const [key, tmpl] of Object.entries(templates)) {
  const name = snakeToPascal(key);
  const args = templateArgs(tmpl);
  // Special-case output enable: take bool, map to ON/OFF
  if (key === "psu_output_enable") {
    csScpi += `    public static string PsuOutputEnable(uint channel, bool enabled) => $":OUTP{channel} {(enabled ? "ON" : "OFF")}";\n`;
    continue;
  }
  if (key === "fgen_output_enable") {
    csScpi += `    public static string FgenOutputEnable(bool enabled) => $":OUTP {(enabled ? "ON" : "OFF")}";\n`;
    continue;
  }
  const csParams = args.map((a) => `${csArgType(a)} ${snakeToCamel(a)}`).join(", ");
  let interp = tmpl;
  for (const a of args) {
    const token = csArgType(a) === "double"
      ? `{ScpiFormat.Double(${snakeToCamel(a)})}`
      : `{${snakeToCamel(a)}}`;
    interp = interp.replaceAll(`{${a}}`, token);
  }
  if (interp.includes('"') && !interp.includes("ScpiFormat")) {
    // Prefer concatenation when the SCPI template embeds quotes
    const parts = interp.split(/(\{[a-zA-Z][a-zA-Z0-9]*\})/);
    const expr = parts.map((p) => {
      if (/^\{[a-zA-Z][a-zA-Z0-9]*\}$/.test(p)) return p.slice(1, -1);
      return JSON.stringify(p);
    }).join(" + ");
    csScpi += `    public static string ${name}(${csParams}) => ${expr};\n`;
  } else {
    csScpi += `    public static string ${name}(${csParams}) => $"${interp}";\n`;
  }
}

csScpi += "\n";
for (const [key, value] of Object.entries(consts)) {
  csScpi += `    public const string ${snakeToPascal(key)} = "${value}";\n`;
}
csScpi += "}\n";

const rustProbesPath = new URL(
  "crates/instrument-core/src/classifier/probes.rs",
  root,
);
const rustScpiPath = new URL(
  "crates/instrument-core/src/scpi_commands.rs",
  root,
);
const csProbesPath = new URL(
  "dotnet/src/InstrumentComponents/Classifier/CapabilityProbes.cs",
  root,
);
const csScpiPath = new URL(
  "dotnet/src/InstrumentComponents/Classes/ScpiCommands.cs",
  root,
);

await Deno.writeTextFile(rustProbesPath, rustProbes);
await Deno.writeTextFile(rustScpiPath, rustScpi);
await Deno.writeTextFile(csProbesPath, csProbes);
await Deno.writeTextFile(csScpiPath, csScpi);
await rustfmtGenerated([rustProbesPath, rustScpiPath]);

console.log("Wrote", rustProbesPath.pathname);
console.log("Wrote", rustScpiPath.pathname);
console.log("Wrote", csProbesPath.pathname);
console.log("Wrote", csScpiPath.pathname);
